# Generated by Django 5.0.2 on 2024-02-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200, verbose_name='название статьи'),
        ),
    ]
